import { Action, ThunkAction } from '@reduxjs/toolkit';
import { TypedUseSelectorHook } from 'react-redux';
declare const store: import("@reduxjs/toolkit").EnhancedStore<{
    accReceipt: import("../features/accReceipt/accReceiptSlice").AccReceiptState;
    auth: import("../features/auth/authSlice").AuthState;
    business: import("../features/business/businessSlice").BusinessState;
    businessType: import("../features/businessType/businessTypeSlice").BusinessTypeState;
    budgetAssess: import("../features/budgetAssess/budgetAssessSlice").BudgetAssessState;
    bussCurrBalance: import("../features/bussCurrBalance/bussCurrBalanceSlice").BussCurrBalanceState;
    electoralArea: import("../features/electoralArea/electoralAreaSlice").ElectoralAreaState;
    gradeFees: import("../features/gradeFees/gradeFeesSlice").GradeFeesState;
    gradeRate: import("../features/gradeRate/gradeRateSlice").GradeRateState;
    offBudgetAssessment: import("../features/offBudgetAssessment/offBudgetAssessmentSlice").OffBudgetAssessmentState;
    officerAssessment: import("../features/officerAssessment/officerAssessmentSlice").PaymentsState;
    officerBudgetWeekly: import("../features/officerBudgetWeekly/officerBudgetWeeklySlice").OfficerBudgetWeeklyState;
    officer: import("../features/officer/officerSlice").OfficerState;
    operatorDefinition: import("../features/operatorDefinition/operatorDefinitionSlice").OperatorState;
    operatorPermission: import("../features/operatorPermission/operatorPermissionSlice").OperatorPermissionState;
    paymentReport: import("../features/paymentReport/paymentReportSlice").PaymentReportState;
    propertyBalance: import("../features/propertyBalance/propertyBalanceSlice").PropertyBalanceState;
    propertyClass: import("../features/propertyClass/propertyClassSlice").PropertyClassState;
    propertyCollectorElectoralarea: import("../features/propertyCollectorElectoralArea/propertyCollectorElectoralAreaSlice").PropertyCollectorElectoralareaState;
    propertyOfficerAssessment: import("../features/propertyOfficerAssessment/propertyOfficerAssessmentSlice").PropertyOfficerAssessmentState;
    propertyOfficerBudget: import("../features/propertyOfficerBudget/propertyOfficerBudgetSlice").PropertyOfficerBudgetState;
    propertyOfficer: import("../features/propertyOfficer/propertyOfficerSlice").PropertyOfficerState;
    propertyRate: import("../features/propertyRate/propertyRateSlice").PropertyRateState;
    propertyType: import("../features/propertyType/propertyTypeSlice").PropertyTypeState;
    propertyUse: import("../features/propertyUse/propertyUseSlice").PropertyUseState;
    receipt: import("../features/receipt/receiptSlice").ReceiptState;
    transSavings: import("../features/transSavings/transSavingsSlice").TransSavingsState;
    photos: import("../features/photos/photosSlice").PhotosState;
    busPayments: import("../features/busPayments/busPaymentsSlice").BusPaymentsState;
    officerBudget: import("../features/officerBudget/officerBudgetSlice").OfficerBudgetState;
    collectorElectoralArea: import("../features/collectorElectoralarea/collectorElectoralAreaSlice").CollectorElectoralAreaState;
    balance: import("../features/balance/balanceSlice").BalanceState;
    busTypedetailedReport: import("../features/busTypeDetailedReport/busTypeDetailedReportSlice").ReportsState;
    reports: import("../features/managementSummariseReport.ts/BusTypeSummaryReportSlice").ReportsState;
}, import("redux").UnknownAction, import("@reduxjs/toolkit").Tuple<[import("redux").StoreEnhancer<{
    dispatch: import("redux-thunk").ThunkDispatch<{
        accReceipt: import("../features/accReceipt/accReceiptSlice").AccReceiptState;
        auth: import("../features/auth/authSlice").AuthState;
        business: import("../features/business/businessSlice").BusinessState;
        businessType: import("../features/businessType/businessTypeSlice").BusinessTypeState;
        budgetAssess: import("../features/budgetAssess/budgetAssessSlice").BudgetAssessState;
        bussCurrBalance: import("../features/bussCurrBalance/bussCurrBalanceSlice").BussCurrBalanceState;
        electoralArea: import("../features/electoralArea/electoralAreaSlice").ElectoralAreaState;
        gradeFees: import("../features/gradeFees/gradeFeesSlice").GradeFeesState;
        gradeRate: import("../features/gradeRate/gradeRateSlice").GradeRateState;
        offBudgetAssessment: import("../features/offBudgetAssessment/offBudgetAssessmentSlice").OffBudgetAssessmentState;
        officerAssessment: import("../features/officerAssessment/officerAssessmentSlice").PaymentsState;
        officerBudgetWeekly: import("../features/officerBudgetWeekly/officerBudgetWeeklySlice").OfficerBudgetWeeklyState;
        officer: import("../features/officer/officerSlice").OfficerState;
        operatorDefinition: import("../features/operatorDefinition/operatorDefinitionSlice").OperatorState;
        operatorPermission: import("../features/operatorPermission/operatorPermissionSlice").OperatorPermissionState;
        paymentReport: import("../features/paymentReport/paymentReportSlice").PaymentReportState;
        propertyBalance: import("../features/propertyBalance/propertyBalanceSlice").PropertyBalanceState;
        propertyClass: import("../features/propertyClass/propertyClassSlice").PropertyClassState;
        propertyCollectorElectoralarea: import("../features/propertyCollectorElectoralArea/propertyCollectorElectoralAreaSlice").PropertyCollectorElectoralareaState;
        propertyOfficerAssessment: import("../features/propertyOfficerAssessment/propertyOfficerAssessmentSlice").PropertyOfficerAssessmentState;
        propertyOfficerBudget: import("../features/propertyOfficerBudget/propertyOfficerBudgetSlice").PropertyOfficerBudgetState;
        propertyOfficer: import("../features/propertyOfficer/propertyOfficerSlice").PropertyOfficerState;
        propertyRate: import("../features/propertyRate/propertyRateSlice").PropertyRateState;
        propertyType: import("../features/propertyType/propertyTypeSlice").PropertyTypeState;
        propertyUse: import("../features/propertyUse/propertyUseSlice").PropertyUseState;
        receipt: import("../features/receipt/receiptSlice").ReceiptState;
        transSavings: import("../features/transSavings/transSavingsSlice").TransSavingsState;
        photos: import("../features/photos/photosSlice").PhotosState;
        busPayments: import("../features/busPayments/busPaymentsSlice").BusPaymentsState;
        officerBudget: import("../features/officerBudget/officerBudgetSlice").OfficerBudgetState;
        collectorElectoralArea: import("../features/collectorElectoralarea/collectorElectoralAreaSlice").CollectorElectoralAreaState;
        balance: import("../features/balance/balanceSlice").BalanceState;
        busTypedetailedReport: import("../features/busTypeDetailedReport/busTypeDetailedReportSlice").ReportsState;
        reports: import("../features/managementSummariseReport.ts/BusTypeSummaryReportSlice").ReportsState;
    }, undefined, import("redux").UnknownAction>;
}>, import("redux").StoreEnhancer]>>;
export type AppStore = typeof store;
export type AppDispatch = typeof store.dispatch;
export type RootState = ReturnType<typeof store.getState>;
export type AppThunk<ThunkReturnType = void> = ThunkAction<ThunkReturnType, RootState, unknown, Action>;
export declare const useAppDispatch: () => import("redux-thunk").ThunkDispatch<{
    accReceipt: import("../features/accReceipt/accReceiptSlice").AccReceiptState;
    auth: import("../features/auth/authSlice").AuthState;
    business: import("../features/business/businessSlice").BusinessState;
    businessType: import("../features/businessType/businessTypeSlice").BusinessTypeState;
    budgetAssess: import("../features/budgetAssess/budgetAssessSlice").BudgetAssessState;
    bussCurrBalance: import("../features/bussCurrBalance/bussCurrBalanceSlice").BussCurrBalanceState;
    electoralArea: import("../features/electoralArea/electoralAreaSlice").ElectoralAreaState;
    gradeFees: import("../features/gradeFees/gradeFeesSlice").GradeFeesState;
    gradeRate: import("../features/gradeRate/gradeRateSlice").GradeRateState;
    offBudgetAssessment: import("../features/offBudgetAssessment/offBudgetAssessmentSlice").OffBudgetAssessmentState;
    officerAssessment: import("../features/officerAssessment/officerAssessmentSlice").PaymentsState;
    officerBudgetWeekly: import("../features/officerBudgetWeekly/officerBudgetWeeklySlice").OfficerBudgetWeeklyState;
    officer: import("../features/officer/officerSlice").OfficerState;
    operatorDefinition: import("../features/operatorDefinition/operatorDefinitionSlice").OperatorState;
    operatorPermission: import("../features/operatorPermission/operatorPermissionSlice").OperatorPermissionState;
    paymentReport: import("../features/paymentReport/paymentReportSlice").PaymentReportState;
    propertyBalance: import("../features/propertyBalance/propertyBalanceSlice").PropertyBalanceState;
    propertyClass: import("../features/propertyClass/propertyClassSlice").PropertyClassState;
    propertyCollectorElectoralarea: import("../features/propertyCollectorElectoralArea/propertyCollectorElectoralAreaSlice").PropertyCollectorElectoralareaState;
    propertyOfficerAssessment: import("../features/propertyOfficerAssessment/propertyOfficerAssessmentSlice").PropertyOfficerAssessmentState;
    propertyOfficerBudget: import("../features/propertyOfficerBudget/propertyOfficerBudgetSlice").PropertyOfficerBudgetState;
    propertyOfficer: import("../features/propertyOfficer/propertyOfficerSlice").PropertyOfficerState;
    propertyRate: import("../features/propertyRate/propertyRateSlice").PropertyRateState;
    propertyType: import("../features/propertyType/propertyTypeSlice").PropertyTypeState;
    propertyUse: import("../features/propertyUse/propertyUseSlice").PropertyUseState;
    receipt: import("../features/receipt/receiptSlice").ReceiptState;
    transSavings: import("../features/transSavings/transSavingsSlice").TransSavingsState;
    photos: import("../features/photos/photosSlice").PhotosState;
    busPayments: import("../features/busPayments/busPaymentsSlice").BusPaymentsState;
    officerBudget: import("../features/officerBudget/officerBudgetSlice").OfficerBudgetState;
    collectorElectoralArea: import("../features/collectorElectoralarea/collectorElectoralAreaSlice").CollectorElectoralAreaState;
    balance: import("../features/balance/balanceSlice").BalanceState;
    busTypedetailedReport: import("../features/busTypeDetailedReport/busTypeDetailedReportSlice").ReportsState;
    reports: import("../features/managementSummariseReport.ts/BusTypeSummaryReportSlice").ReportsState;
}, undefined, import("redux").UnknownAction> & import("redux").Dispatch<import("redux").UnknownAction>;
export declare const useAppSelector: TypedUseSelectorHook<RootState>;
export default store;
