services:
  - type: web
    name: backend
    buildCommand: "corepack enable && corepack prepare yarn@stable --activate && yarn install && yarn workspace backend build"
    startCommand: "yarn workspace backend start"
    envVars:
      - key: NODE_VERSION
        value: "20"

  - type: web
    name: frontend
    buildCommand: "corepack enable && corepack prepare yarn@stable --activate && yarn install && yarn workspace frontend build"
    startCommand: "yarn workspace frontend start"
    envVars:
      - key: NODE_VERSION
        value: "20"



