import { jsxs as _jsxs, jsx as _jsx } from "react/jsx-runtime";
var PaymentsTable = function (_a) {
    var busPaymentsData = _a.busPaymentsData;
    var totalPaid = busPaymentsData.reduce(function (accumulator, payment) {
        // Check if payment.paidamount is a number, if not, default to 0
        return accumulator + (typeof payment.paidAmount === 'number' ? payment.paidAmount : 0);
    }, 0);
    return (_jsx("div", { className: "table-responsive", children: _jsxs("table", { className: "table table-bordered", style: { fontSize: '0.8em' }, children: [" ", _jsxs("thead", { children: [_jsx("tr", { children: _jsxs("th", { colSpan: 8, className: "text-center", style: { color: 'red', fontWeight: 'bold', fontSize: '1em' }, children: ["Total Paid: ", totalPaid] }) }), _jsxs("tr", { children: [_jsx("th", { style: { fontSize: '0.8em' }, children: "Business Number" }), _jsx("th", { style: { fontSize: '0.8em' }, children: "Officer Name" }), _jsx("th", { style: { fontSize: '0.8em' }, children: "Paid Amount" }), _jsx("th", { style: { fontSize: '0.8em' }, children: "Month Paid" }), _jsx("th", { style: { fontSize: '0.8em' }, children: "Transaction Date" }), _jsx("th", { style: { fontSize: '0.8em' }, children: "Fiscal Year" })] })] }), _jsx("tbody", { children: busPaymentsData.length > 0 ? (busPaymentsData.map(function (payment, index) { return (_jsxs("tr", { children: [_jsx("td", { style: { fontSize: '0.8em' }, children: payment.buss_no }), _jsx("td", { style: { fontSize: '0.8em' }, children: payment.officer_no }), _jsx("td", { style: { fontSize: '0.8em' }, children: payment.paidAmount }), _jsx("td", { style: { fontSize: '0.8em' }, children: payment.monthpaid }), _jsx("td", { style: { fontSize: '0.8em' }, children: new Date(payment.transdate).toLocaleDateString() }), _jsx("td", { style: { fontSize: '0.8em' }, children: payment.fiscal_year }), _jsx("td", { style: { fontSize: '0.8em' }, children: payment.electoral_area })] }, index)); })) : (_jsx("tr", { children: _jsx("td", { colSpan: 8, className: "text-center", style: { fontSize: '0.8em' }, children: "No payments found" }) })) })] }) }));
};
export default PaymentsTable;
